### create
POST http://localhost:8081/hugs
Content-Type: application/json

{
  "from": "GSO"
}

### read all hugs
GET http://localhost:8081/hugs

### stream hugs
GET http://localhost:8081/hugs/stream
